---
language: python

# Run jobs in VMs - sudo is required by ansible tests.
sudo: required

# Install ansible
addons:
  apt:
    packages:
      - gcc
      - python-apt
      - python-virtualenv
      - realpath

# Create a build matrix for the different test jobs.
matrix:
  include:
    # Run Python style checks.
    - python: 3.5
      env: TOX_ENV=pep8
    # Run Ansible linting.
    - python: 3.5
      env: TOX_ENV=alint
    # Run Python 3.5 tests.
    - python: 3.5
      env: TOX_ENV=py35
    # Run Python 2.7 tests.
    - python: 2.7
      env: TOX_ENV=py27
    # Run coverage checks.
    - python: 3.5
      env: TOX_ENV=cover
    # Generate docs.
    - python: 3.5
      env: TOX_ENV=docs

install:
  # Install tox in a virtualenv to ensure we have an up to date version.
  - pip install -U pip
  - pip install tox

script:
  # Run the tox environment.
  - tox -e ${TOX_ENV}
