---
- name: Set common strings
  set_fact:
    # vbmcd should already be running, so --no-daemon stops vbmc from spawning
    # another instance of the daemon.
    cmd: "'{{ vbmc_virtualenv_path }}/bin/vbmc' --no-daemon"
    log_arg: "--log-file '{{ vbmc_log_directory }}/vbmc-{{ domain }}.log'"

# Even if the domain is present in VBMC, we can't guarantee that it's
# configured correctly. It's easiest to delete and re-add it; this should
# involve minimal downtime.
- name: Ensure domain is stopped and deleted in VBMC
  command: >-
    {{ cmd }} {{ item }} '{{ domain }}' {{ log_arg }}
  loop:
    - stop
    - delete
  register: res
  changed_when: res.rc != 0
  failed_when:
    - res.rc != 0
    - "'No domain with matching name' not in res.stderr"
  become: true

- name: Ensure domain is added to VBMC
  command: >-
    {{ cmd }} add '{{ domain }}'
      --port {{ port }}
      --username '{{ vbmc_ipmi_username }}'
      --password '{{ vbmc_ipmi_password }}'
      --address {{ vbmc_ipmi_listen_address }}
      {{ log_arg }}
  become: true

- name: Ensure domain is started in VBMC
  command: >
    {{ cmd }} start '{{ domain }}' {{ log_arg }}
  become: true
