---
- name: Install the Delorean dependencies repository
  become: true
  get_url:
    url: "https://trunk.rdoproject.org/centos{{ ansible_facts.distribution_major_version }}-master/delorean-deps.repo"
    dest: /etc/yum.repos.d/
  when:
    - ansible_facts.os_family == "RedHat"

- name: Install Open vSwitch
  become: true
  package:
    name: "{{ openvswitch_package_name }}"
    state: present
  register: result
  until: result is success
  retries: 3

- name: Start Open vSwitch service
  become: true
  service:
    name: "{{ openvswitch_service_name }}"
    state: started
