---
- name: Perform deployment host configuration
  import_playbook: deploy_hosts.yml

- name: Perform deployment node configuration
  import_playbook: deploy_nodes.yml

- name: Enrol nodes in Ironic
  import_playbook: enrol_nodes.yml

- name: Register flavors in Nova
  import_playbook: register_flavors.yml
