---
- hosts: all
  tasks:
    - include_tasks: host_setup.yml

- hosts: libvirt
  tasks:
    - name: Configure host as a Libvirt/QEMU/KVM hypervisor
      include_role:
        name: stackhpc.libvirt-host
      vars:
        libvirt_host_pools:
          - name: "{{ libvirt_pool_name }}"
            type: "{{ libvirt_pool_type }}"
            capacity: "{{ libvirt_pool_capacity }}"
            path: "{{ libvirt_pool_path }}"
            mode: "{{ libvirt_pool_mode }}"
            owner: "{{ libvirt_pool_owner }}"
            group: "{{ libvirt_pool_group }}"
        libvirt_host_require_vt: "{{ libvirt_require_vt }}"
