- hosts: localhost
  tasks:
    - name: Load allocations from file
      include_vars:
        file: "{{ allocations_file_path }}"
        name: allocations

- hosts: hypervisors
  vars:
    nodes: >-
      {{ hostvars.localhost.allocations[inventory_hostname]
           | default([]) }}
  tasks:
    - name: Configure veth pairs for each node
      include_role:
        name: veth-pair
      vars:
        veth_pair_ovs_bridge: "{{ item.1 | bridge_name }}"
        veth_pair_ovs_link_name: "{{ item.0 | ovs_link_name(item.1) }}"
        veth_pair_source_link_name: "{{ item.0 | source_link_name(item.1) }}"
        state: "{{ 'absent' if cmd == 'teardown' else 'present' }}"
      # Loop over each physical network for each node allocated to this host.
      # Allocations are stored in localhost's vars.
      loop: >-
        {{ nodes | subelements('physical_networks') }}
