---
- name: Set service name
  set_fact:
    service: vbmcd

- name: Check that enough ports are available for Virtual BMC
  fail: >
    {{ vms | count }} VMs were specified to be created, but only
    {{ vbmc_ipmi_port_range_end - vbmc_ipmi_port_range_start }} ports are
    available for use by Virtual BMC.
  when: (vms | count) > (vbmc_ipmi_port_range_end - vbmc_ipmi_port_range_start)

- name: Ensure Virtual BMC systemd service is configured
  template:
    src: templates/{{ item }}.j2
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: 0644
  become: true
  register: vbmc_service_file
  loop:
    - "{{ service }}.service"

- name: Ensure Virtual BMC systemd service is started and enabled
  systemd:
    name: "{{ service }}"
    enabled: yes
    state: started
    daemon_reload: "{{ vbmc_service_file.changed }}"
  become: true

- include_tasks: vm_virtualbmc.yml
  vars:
    vm: "{{ vm }}"
    port: "{{ vbmc_ipmi_port_range_start + port_offset }}"
  loop: "{{ vms }}"
  loop_control:
    loop_var: vm
    index_var: port_offset
