---
# This is useful to get a uniquely generated temporary path.
- name: Create temporary file for pip requirements
  tempfile:
  register: req_file

- name: Copy requirements file to temporary location
  copy:
    src: requirements.txt
    dest: "{{ req_file.path }}"

- name: Ensure Python requirements are installed
  pip:
    requirements: "{{ req_file.path }}"
    extra_args: >-
      -c {{ ironic_python_upper_constraints_url }}
    virtualenv: "{{ ironic_virtualenv_path }}"

- name: Configure Ironic node enrolment
  include_tasks: node.yml
  vars:
    node: "{{ ironic_node }}"
    ipmi_port: >-
      {{ hostvars[ironic_hypervisor].ipmi_port_range_start + port_offset }}
  loop: "{{ ironic_nodes | sort(attribute='name') }}"
  loop_control:
    loop_var: ironic_node
    index_var: port_offset
  # If no ironic_config options were set, this means that enrolment should not
  # be performed.
  when: "'ironic_config' in ironic_node"
