---
- name: Ensure Python requirements are installed
  pip:
    requirements: "{{ '/'.join([role_path, 'files', 'requirements.txt']) }}"
    extra_args: >-
      -c {{ ironic_python_upper_constraints_url }}
    virtualenv: "{{ ironic_virtualenv_path }}"

- name: Enrol the Ironic nodes
  include_tasks: node.yml
  vars:
    node: "{{ ironic_node }}"
    ipmi_port: >-
      {{ hostvars[ironic_hypervisor].ipmi_port_range_start + port_offset }}
  loop: "{{ ironic_nodes | sort(attribute='name') }}"
  loop_control:
    loop_var: ironic_node
    index_var: port_offset
  # If no ironic_config options were set, this means that enrolment should not
  # be performed.
  when: "'ironic_config' in ironic_node"
