---
- project:
    templates:
      - build-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-python35-jobs
      - openstack-python-jobs
    check:
      jobs:
        - build-openstack-releasenotes
        - tenks-tox-ansible-lint
    gate:
      queue: tenks
      jobs:
        - build-openstack-releasenotes
        - tenks-tox-ansible-lint
