---
- project:
    templates:
      - openstack-cover-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3

    check:
      jobs:
        - tenks-tox-ansible-lint
        - tenks-deploy-teardown-ovs-centos8
        - tenks-deploy-teardown-ovs-ubuntu
        - tenks-deploy-teardown-linuxbridge-centos8
        - tenks-deploy-teardown-linuxbridge-ubuntu
        # Until we have ironic jobs using tenks, gate on the kayobe overcloud
        # deploy job, which uses tenks to test bare metal compute provisioning.
        - kayobe-overcloud-centos8
    gate:
      queue: tenks
      jobs:
        - tenks-tox-ansible-lint
        - tenks-deploy-teardown-ovs-centos8
        - tenks-deploy-teardown-ovs-ubuntu
        - tenks-deploy-teardown-linuxbridge-centos8
        - tenks-deploy-teardown-linuxbridge-ubuntu
        # Until we have ironic jobs using tenks, gate on the kayobe overcloud
        # deploy job, which uses tenks to test bare metal compute provisioning.
        - kayobe-overcloud-centos8
