---
- project:
    templates:
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - openstack-cover-jobs
      - openstack-python35-jobs
      - openstack-python-jobs
    check:
      jobs:
        - tenks-tox-ansible-lint
        - tenks-deploy-teardown-centos
        - tenks-deploy-teardown-ubuntu
    gate:
      queue: tenks
      jobs:
        - tenks-tox-ansible-lint
        - tenks-deploy-teardown-centos
        - tenks-deploy-teardown-ubuntu
