---
- hosts: hypervisors
  vars:
    ansible_become: true
  tasks:
    - block:
        - name: Install the Delorean repositories
          get_url:
            url: "{{ item }}"
            dest: /etc/yum.repos.d/
          with_items:
            - "https://trunk.rdoproject.org/centos{{ ansible_facts.distribution_major_version }}-master/consistent/delorean.repo"
            - "https://trunk.rdoproject.org/centos{{ ansible_facts.distribution_major_version }}-master/delorean-deps.repo"

        - name: Install Open vSwitch
          package:
            name: openvswitch

        - name: Start openvswitch service
          service:
            name: openvswitch
            state: started
      when:
        - ansible_facts.os_family == "RedHat"

    - block:
        - name: Install packages
          package:
            name: "{{ item }}"
          register: result
          until: result is success
          retries: 3
          with_items:
            - openvswitch-switch
            - openvswitch-common

        - name: Start openvswitch service
          service:
            name: openvswitch-switch
            state: started
      when: ansible_facts.os_family == "Debian"
